### PR TITLE
Bugfix/172 Fixes generic types and non-generic types being collated

### LINKED ISSUE #172: Trim Unused Types removes classes in use with same name as unreferenced classes
## Issue
C# allows classes with the same identifier, if they have a different set of generic parameters.

When the MDK deploys a script with the setting 'Trim Unused Types' enabled, it removes declarations of classes are not references in executable code **as well as** any other class that shares the same name, regardless of the generic parameters it has.

## Example
```
using Sandbox.ModAPI.Ingame;

namespace IngameScript
{
	partial class Program : MyGridProgram
	{
		class DissapearingClass { }

		class DissapearingClass<T> { }

		public void Main(string argument, UpdateType updateSource)
		{
			var instance = new DissapearingClass();
		}
	}
}
```

becomes

```
public void Main(string argument, UpdateType updateSource)
{
	var instance = new DissapearingClass();
}
```

MDK should preserve the classes that are referenced.

## Impact
Some generic classes inherit a non-generic class as a pattern e.g. `IEnumerable`, `IEnumerable<T>`. They typically share the same name, and if one of the set of classes is not being used, both will disappear, causing compilation issues in space engineers.

## Workarounds:
  - Disabling Trim Unused Types
  - Ensuring each class has a unique name

### PR DESCRIPTION
**Pull request by lukekaalim**
Apologies in advance if I've missed a process or anything since this is my first PR.

This PR edits the 'naming' of types to determine if they're being referenced or not, and thus if they can be trimmed.
If a symbol is a reference of a type, then we defer the naming of that symbol to the type itself. (note that First() is used since in the case of partial classes, there might be multiple locations it's defined, but any one of them should all work for the purpose of the class's name)
This PR also makes an edit to the naming of types, including the `<T>` generic parameters if the type has any.

Thus, a reference should generate the same name as the type declaration, and the type declaration should respect generics.

Should fix #172 

Let me know if you want me to add some test cases or anything, though I don't actually program in C# so I might need some handholding for more advanced things.

### CODE REVIEW

File: Source/MDK/Build/AnalysisExtensions.cs [hunk 1]
```diff
@@ -149,7 +160,7 @@ static string GetFullNameCore(TypeDeclarationSyntax typeDeclaration, Declaration
         {
             var ident = new List<string>(10)
             {
-                typeDeclaration.Identifier.ToString()
+                $"{typeDeclaration.Identifier}{typeDeclaration.TypeParameterList}"
```
Comment (lukekaalim) [inline Source/MDK/Build/AnalysisExtensions.cs]: I actually don't know best practices for string concatenation. Is this alright?

**Comment by malware-dev** [comment]
Heh...

If only every bug report came with its own fix like this 😄 

I'll need to take a good look before merging of course. But thank you very much!
